export const chatGroups = [
  {
    id: '1',
    name: 'Girl WhatsApp number',
    lastMessage: ' available! Join now.',
    time: '12:30 PM',
    unreadCount: 2480,
    avatar: 'https://play-lh.googleusercontent.com/Go_o7_v7F-uHIYf4uEkFcLJl5WtajBcz0-I1qFHrm0kb2lPrVepanIU5qEj2Hh1GuU8',
  },
  {
    id: '2',
    name: 'Private Video Group',
    lastMessage: 'Latest video',
    time: '11:45 AM',
    unreadCount: 1850,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMpXrdPI8vSdj21nCCE4RtJu7wGiaUh_95UQ&s',
  },
  {
    id: '3',
    name: 'ikram video group',
    lastMessage: 'Breaking: New pic!',
    time: '11:15 AM',
    unreadCount: 3250,
    avatar: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgoNU_Zn_UjybL65v3BoM7Rh4wV2KW2dh_sU9dWo-yh8Qc4Cw__u4tl54TYAKvDZ1I_DdH7D-kwK1baCqfE1AsFXKW0yCXIcXvh7yzaK_hZu6ZBw01Q8UwgsAi3yZ_Ay_yD4o-NErj2am7F/s388-rw/Aqsa+Khan.webp',
  },
  {
    id: '4',
    name: 'online earning',
    lastMessage: 'Exclusive: Premium earning ',
    time: '10:30 AM',
    unreadCount: 1680,
    avatar: 'https://play-lh.googleusercontent.com/JLSVt83UixrEbzd7s1JV47x2bHUpWP6pncRzvY7ywiaQ_5QTU7SQRyqz2G00fSsnzw',
  },
  {
    id: '5',
    name: '📈 SUB4SUB FREE ',
    lastMessage: 'youtube subscribers free',
    time: '10:15 AM',
    unreadCount: 4200,
    avatar: 'https://play-lh.googleusercontent.com/_we2DDWQhDorycDTl4SZjb2PFq75O4xOaAJUpiDHERGBJ4L1gvgQeGXwEJPX4MSf_RPq',
  },
  {
    id: '6',
    name: '🔥 Only Girl Group',
    lastMessage: ' New Only Girl Group',
    time: '9:45 AM',
    unreadCount: 2890,
    avatar: 'https://i.pinimg.com/originals/c8/d1/c4/c8d1c47c4ac2c669aaac521e08069d97.jpg',
  },
  {
    id: '7',
    name: 'Girl WhatsApp group',
    lastMessage: 'Latest: Girl group',
    time: '9:30 AM',
    unreadCount: 1920,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRF2k69k0T49cGwkFeDPDcJLbnzdMceCVTJkg&s',
  },
  {
    id: '8',
    name: 'Girl Vs Man',
    lastMessage: 'Exclusive: partnership',
    time: '9:15 AM',
    unreadCount: 3480,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXqeW0aj91NbBbQ83EdfVlgtes9C2F_4LLFw&s',
  },
  {
    id: '9',
    name: '📱 Mobile video ',
    lastMessage: 'New: Mobile-video',
    time: '8:45 AM',
    unreadCount: 2750,
    avatar: 'https://yt3.googleusercontent.com/K8WVrQAQHTTwsHEtisMYcNai7p7XIlyEAdZg86qYw78ye57r5DRemHQ9Te4PcD_v98HB-ZvQjQ=s900-c-k-c0x00ffffff-no-rj',
  },
  {
    id: '10',
    name: '🎯 Target pic',
    lastMessage: 'Update: New geo ',
    time: '8:30 AM',
    unreadCount: 1580,
    avatar: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEixTmXVBp8nVPgjv3jz1VBZsx0K8qLX1vtC7TDmA5E-UGhNf6SW2QjwJGzeYIhiDpvqNLQTScZYGtc2F3erPnsnS3L3b26d8OekX2ZThTfDZlJ0XowD5AB2LigAPGCmklCIphNxofFcm2lIv35ZCfmSuUeDoYCy34OlWcPA4rk3u7tZtrXZKS9PLHtP/s886/ep89xg4ijfq28lyazwq21xrk3otx314c.jpg',
  },
];